build: off

# Specify which branches/tags that we do not want to be built: r5.0.0-M5
branches:
  except:
    - /^r\d.*$/

install:
# Turn off JDK installation from chocolatey
#  - cinst jdk10 -params 'installdir=C:\\jdk10'
#  - SET JAVA_HOME=C:\jdk10
# Use pre-installed JDK
  - SET JAVA_HOME="C:\Program Files\Java\jdk10"
  - SET PATH=%JAVA_HOME%\bin;%PATH%

test_script:
  - gradlew --no-daemon -version
  - gradlew --no-daemon --stacktrace build publishToMavenLocal
  - gradlew --no-daemon --stacktrace -Dplatform.tooling.support.tests.enabled=true build
